on:
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
          config: >-
            p/security-audit 
            p/secrets
            r/javascript.aws-lambda.security.knex-sqli.knex-sqli
            
    - name: Result artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Result
        path: |
          ./semgrep-report        
    

