name: Weekly vulnerability scan
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * SUN'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  repo-scan-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Installing semgrep using pip
      run: pip3 install semgrep

      # python-command-injection is only the first ruleset we are making active
      # more soon to be added
    - name: Run semver on diff between current and develop branch
      run: |
        semgrep --config="r/javascript.audit.detect-replaceall-sanitization.detect-replaceall-sanitization" --json > world2.json
    
#     - name: Change path to artifa
#       run: echo hello > semgrep-result/world.txt
      
    - name: Archive vulnerability scan results
      uses: actions/upload-artifact@v2
      with:
        name: Semgrep report
        path: world2.json
  
      
#     - name: Check result and exit
#       run: |
#         RESULT_LEN=$(cat semver.txt | wc -l)
#         rm semver.txt
#         if [[ $RESULT_LEN == 0 ]]; then
#           exit 0 
#         else
#           echo "Potential vulnerabilities found"
#           echo "Check the audit report and fix"         
#           exit 1
#         fi
