name: Weekly vulnerability scan
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * SUN'

jobs:
  repo-scan-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Installing semgrep using pip
      run: pip3 install semgrep

    - name: Checkout
      uses: actions/checkout@v2
      
    
    - name: Change path to artiface
      run: mkdir -p semgrep-result
#     - name: Export repo name to env
#       run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
#       shell: bash

      # python-command-injection is only the first ruleset we are making active
      # more soon to be added
    - name: Run semver on diff between current and develop branch
      run: |
        semgrep --config p/owasp-top-ten --json > semgrep-result/world.txt
    

      
#     - name: Change path to artifa
#       run: echo hello > semgrep-result/world.txt
      
    - name: Archive vulnerability scan results
      uses: actions/upload-artifact@v2
      with:
        name: Semgrep report
        path: |
          semgrep-result/world.txt
          

    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'semgrep-result/world.txt'  
      
#     - name: Check result and exit
#       run: |
#         RESULT_LEN=$(cat semver.txt | wc -l)
#         rm semver.txt
#         if [[ $RESULT_LEN == 0 ]]; then
#           exit 0 
#         else
#           echo "Potential vulnerabilities found"
#           echo "Check the audit report and fix"         
#           exit 1
#         fi
